### PR TITLE
Fix TCP close behavior in case of cuncurrent read+write operations

### LINKED ISSUE #1726: TCP concurrent read/write not properly terminated if peer closes connection
Most likely the cause for #1724. This happens for the libevent and libasync drivers, not for vibe-core.

### PR DESCRIPTION
**Pull request by s-ludwig**
Fixes #1726 and possibly #1724.

### CODE REVIEW

File: core/vibe/core/drivers/libasync.d [hunk 1]
```diff
@@ -1315,6 +1329,7 @@ final class LibasyncTCPConnection : TCPConnection/*, Buffered*/ {
 	}
 
 	void acquireReader() {
+		assert(!m_settings.writer.isWaiting, "Acquiring reader that is already in use.");
```
Comment (ZombineDev) [inline core/vibe/core/drivers/libasync.d]: I have almost no knowledge of the code, but shouldn't this be `m_settings.reader.isWaiting`?

Comment (s-ludwig) [inline core/vibe/core/drivers/libasync.d]: I was about to refactor those methods into the `Waiter` struct... and then went the copy/past route ;)

**Comment by s-ludwig** [comment]
Okay, fixed and passing. Merging in.
