### PR TITLE
fix some rest js client problems

### LINKED ISSUE #1565: error in serveRestJSClient
[here](https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/web/rest.d#L246) and [here](https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/web/rest.d#L253) not specified template parameter `I`

### PR DESCRIPTION
**Pull request by deviator**
fix #1565
some problem from #1564 fix also

### CODE REVIEW

**Comment by deviator** [comment]
ping @s-ludwig

**Comment by s-ludwig** [comment]
The Travis failure is due to a flaky test - I've restarted the test run now and will remove that specific test.

Changes look good, except for the mentioned if/else swap. Maybe the three additional parameters could be grouped inside of a `JSRestInterfaceSettings` class - it seems like more options could come in handy later on.

**Comment by deviator** [comment]
@s-ludwig it's ok?

**Comment by WowVeryLogin** [comment]
Ping @s-ludwig I've encountred bug, described in issue #1564 and it's very important for owr company to continue to work on project, so pls fix this stuff as soon as you can

**Comment by s-ludwig** [comment]
Looks good to merge, thanks! I'll just make the `parent` parameter private for now/remove it from the settings class, so that it doesn't become a burden w.r.t. backwards compatibility.

File: source/vibe/web/internal/rest/jsclient.d [hunk 1]
```diff
@@ -30,81 +58,98 @@ import std.conv : to;
...
-				if (!p.isParameter) output.serializeToJson(p.text);
-				else output.formattedWrite("encodeURIComponent(toRestString(%s))", p.text);
+				fout.put(" + ");
+				if (!p.isParameter) fout.serializeToJson(p.text);
+				else fout.formattedWrite("encodeURIComponent(toRestString(%s))", p.text);
 			}
-			output.put(";\n");
 		} else {
-			output.formattedWrite("    var url = %s;\n", Json(concatURL(intf.baseURL, route.pattern)));
+			auto rpn = route.parameters
```
Comment (s-ludwig) [inline source/vibe/web/internal/rest/jsclient.d]: Stupid new review feature has eaten my earlier comment...

So this part is strange, because the upper part of the if statement is supposed to be doing what you did in the `else` part. Maybe there is an issue with `route.hasPathPlaceholders`.

Comment (deviator) [inline source/vibe/web/internal/rest/jsclient.d]: I was look to this part, but was confusing by [this](https://github.com/rejectedsoftware/vibe.d/blob/master/source/vibe/web/internal/rest/common.d#L176) and I don't touch this, because I think change in this part can have more complex effects. Is this a bug or only first `id` parameter can be a placeholders by design? If it by design it's doubtful (or I don't understand somethings).

Comment (s-ludwig) [inline source/vibe/web/internal/rest/jsclient.d]: That was indeed broken. I've committed a fix for the `hasPathPlaceholders` computation: https://github.com/rejectedsoftware/vibe.d/commit/f23d7740e7e459e6a890cf6d7ef64bb1b5640402
And also one for the JS URL computation: https://github.com/rejectedsoftware/vibe.d/commit/10e37edd880e3790e5cc6ff7ee89e3018348b3ad

Can you remove the changes in the else block from the PR and rebase?

**Comment by deviator** [comment]
ping @s-ludwig

File: source/vibe/web/internal/rest/jsclient.d [hunk 2]
```diff
@@ -31,85 +59,94 @@ import std.conv : to;
...
-			output.serializeToJson(burl.toString()[0 .. $-1]);
+			fout.serializeToJson(burl.toString()[0 .. $-1]);
 			// and then assemble the full path piece-wise
 			foreach (p; route.fullPathParts) {
-				output.put(" + ");
-				if (!p.isParameter) output.serializeToJson(p.text);
-				else output.formattedWrite("encodeURIComponent(toRestString(%s))", p.text);
+				fout.put(" + ");
+				if (!p.isParameter) fout.serializeToJson(p.text);
+				else fout.formattedWrite("encodeURIComponent(%s)", p.text);
```
Comment (s-ludwig) [inline source/vibe/web/internal/rest/jsclient.d]: I believe the `toRestString` must conceptually stay here, even if the function itself is currently not implemented. At some point it must be made equal to the one defined in the D code base.

Comment (deviator) [inline source/vibe/web/internal/rest/jsclient.d]: I implement this function as [JSON.stringify](https://github.com/rejectedsoftware/vibe.d/pull/1566/files/5745ca3a0af6dbd5e56b3dd08619850f5e69de19#diff-00965ba02c942ce6f16f4106fcd28900R68), because if you want use objects as a parameter of get request you get `object.Object` in params instead `{"x":2, "y":3}` for example. If use it in this case result url has quotes symbols. Maybe need add `toGetParameter` for get request?

Comment (s-ludwig) [inline source/vibe/web/internal/rest/jsclient.d]: The correct semantics are these:
```
	string toRestString(Json value)
	{
		switch (value.type) {
			default: return value.toString();
			case Json.Type.Bool: return value.get!bool ? "true" : "false";
			case Json.Type.Int: return to!string(value.get!long);
			case Json.Type.Float: return to!string(value.get!double);
			case Json.Type.String: return value.get!string;
		}
	}
```
I.e. mostly strings are special cased to omit the quotes. Otherwise it matches `JSON.stringify`.

Comment (deviator) [inline source/vibe/web/internal/rest/jsclient.d]: All of calls `toRestString` returns value to `encodeURIComponent`, maybe `encodeURIComponent` must calls inside of `toRestString`?

Comment (s-ludwig) [inline source/vibe/web/internal/rest/jsclient.d]: That could indeed be done.

**Comment by deviator** [comment]
I beginner in js and can make a mistake, but on my examples it's code works.

**Comment by s-ludwig** [comment]
Looks good, except that arrays also need to be stringified (I'd reverse the condition and stringify everything that is *not* a string).

**Comment by deviator** [comment]
[Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof) arrays `typeof` is `"object"`

**Comment by s-ludwig** [comment]
Oh, alright, didn't expect that! I'll merge then once Travis has finished. Thanks for all the quick follow-up changes!
